name: NovaSecurity
version: 1.0.0
main: de.nova.security.NovaSecurity
api-version: "1.21"
author: Nova Runtime
description: Lightweight security & protection plugin

commands:
  novasecurity:
    description: NovaSecurity main command
    permission: novasecurity.admin

permissions:
  novasecurity.admin:
    default: op
  novasecurity.bypass:
    default: op
